# Generated by Django 5.2.1 on 2025-06-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmacapp', '0005_customproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customproduct',
            old_name='image',
            new_name='main_image',
        ),
        migrations.AddField(
            model_name='customproduct',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Type'),
        ),
        migrations.AddField(
            model_name='customproduct',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
