# Generated by Django 5.2.1 on 2025-07-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmacapp', '0013_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='api_product_code',
            field=models.CharField(blank=True, help_text='Product code from external API (store exactly as received)', max_length=100, null=True, verbose_name='API Product Code'),
        ),
    ]
