# Generated by Django 5.2.1 on 2025-07-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmacapp', '0014_alter_wishlist_api_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='api_product_code',
            field=models.CharField(blank=True, help_text='Product code from external API', max_length=100, null=True, verbose_name='API Product Code'),
        ),
    ]
