# Generated by Django 5.2.1 on 2025-07-15 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysmacapp', '0015_alter_wishlist_api_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='api_products/sub_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_images', to='sysmacapp.editedapiproduct')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
